CREATE TABLE IF NOT EXISTS nft_list (
    nft_id SERIAL PRIMARY KEY,
    id VARCHAR(255),
    evm_asset_id INTEGER NOT NULL,
    contract_id VARCHAR(255) NOT NULL,
    inner_id VARCHAR(255) NOT NULL,
    chain VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    thumbnail_url VARCHAR(255) NOT NULL,
    total_supply INT NOT NULL,
    detail_url VARCHAR(255) NOT NULL,
    collection_id VARCHAR(255) NOT NULL,
    contract_name VARCHAR(255) NOT NULL,
    is_erc1155 BOOLEAN NOT NULL,
    amount INT NOT NULL,
    usd_price DECIMAL(18, 8) NOT NULL,
    attributes JSON NOT NULL,
    pay_token JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (evm_asset_id) REFERENCES evm_assets_debank_v1(evm_asset_id) ON DELETE CASCADE
);