CREATE TABLE IF NOT EXISTS coingecko_price_feed (
  id SERIAL PRIMARY KEY,
  crypto_id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  ticker VARCHAR(255) NOT NULL,
  use_value VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);