name: Go

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
        
    - name: Format
      run: go fmt ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...